node_advertised_committer_rpc_endpoint: "172.17.0.1:50063"

node_committer_rpc_endpoint: "0.0.0.0:50063"

node_management_rpc_endpoint: "0.0.0.0:50093"

node_management_rpc_token: "for_test"

provider_endpoint: "ws://127.0.0.1:8546"

chain_id: 900

controller_address: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933"

controller_relayer_address: "0xf5059a5D33d5853360D16C683c16e67980206f36"

adapter_address: "0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB"

data_path: "./db/data3.sqlite"

logger:
  node_id: 3
  context_logging: false
  log_file_path: log/3/
  rolling_file_size: 10 gb

account:
  private_key: a267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1

listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 1000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  block_time: 3
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 1000
  dkg_wait_for_phase_interval_millis: 1000
  provider_polling_interval_millis: 1000
  provider_reset_descriptor:
    interval_millis: 5000
    max_attempts: 17280
    use_jitter: false
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

relayed_chains:
  - chain_id: 901
    description: "OP"
    provider_endpoint: "ws://127.0.0.1:9546"
    controller_oracle_address: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
    adapter_address: "0x9A676e781A523b5d0C0e43731313A708CB607508"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 3
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false
